### ISSUE TITLE
mpirun: command not found

### ISSUE THREAD

**Issue by ruodingt** [aws-samples/mask-rcnn-tensorflow#16]
Hi, mate

I directly pull the image from `awssamples/mask-rcnn-tensorflow:latest`

And I was following the instruction in the `infra/docker`

Things went well until:

Run training job inside container
```
cd mask-rcnn-tensorflow
infra/docker/train.sh 8 1 250
```

then I got `infra/docker/train.sh: line 17: mpirun: command not found`

Basically I didn't find any installation about MPI in the Dockerfile so I am a bit confused.

**Comment by ruodingt** [comment]
Also I am new to MPI, could please let me know what would happen if I don't use MPI? May I Ask which part of computing is paralleled with MPI

**Comment by YangFei1990** [comment]
Before answering all your questions, we need some clarification from your side:
1. Are you running on AWS? If so, what instance type are you using?
2. How do you pull and run the docker? Did you run the [run.sh](https://github.com/aws-samples/mask-rcnn-tensorflow/blob/master/infra/docker/run.sh)?

**Comment by YangFei1990** [comment]
For MPI:
1. Since we are using Horovod, MPI is required at this point of time. We have plans to support Non-MPI training in the future
2. Essentially with `infra/docker/train.sh 8 1 250` MPI will launch 8 processes where each process contains a copy of the entire model. So for your question
> May I Ask which part of computing is paralleled with MPI

All the computations are paralleled with MPI (Horovod) and we are using data parallelism.

**Comment by ruodingt** [comment]
Hi @YangFei1990 , thank you for getting back to me.

**Comment by YangFei1990** [comment]
>  I am using AMI deep learning base image, with a P3 instance (1 gpu)

I would assume you are using  p3.2xlarge. It is highly recommended to use p3.16xl or p3dn.24xl, otherwise it is possible to hit a memory issue or other problems. Training with 1 gpu will also be very slow (maybe more than 1 week)

>  then run bash train.sh inside the docker container, then it told me MPI command not found (in container)

openMPI should be already installed in the container. You did not see it because it is already installed in the base image which is based on Nvidia's NGC container.

To debug, I would recommend you to try our container first. You can do:

- `docker pull awssamples/mask-rcnn-tensorflow:latest`
- `docker run -it --rm --gpus all --net=host awssamples/mask-rcnn-tensorflow:latest`
- Now you are inside the container, try `mpirun --allow-run-as-root -np 8 echo hello`
- You are supposed to see 8 hellos 

If you can run mpirun in our container, then there must be some conflict for what you have added into the container.

**Comment by YangFei1990** [comment]
Close the issue. Feel free to open it if you have more questions.
